"""add profile_snapshot to pred_user_hb_claims

Revision ID: 4b9d45d4654b
Revises: 2e09a1f6dafd
Create Date: 2026-03-11 16:59:36.276936+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4b9d45d4654b"
down_revision: Union[str, None] = "2e09a1f6dafd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pred_user_hb_claims",
        sa.Column("profile_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pred_user_hb_claims", "profile_snapshot")
    # ### end Alembic commands ###
